#!/bin/bash

project_dir=$(git rev-parse --show-toplevel)

function check_devcontainer_image {
  devcontainer_config="${project_dir}/.devcontainer/devcontainer.json"
  ci_config="${project_dir}/.gitlab-ci.yml"

  devcontainer_image=$(grep x86 ${devcontainer_config} | grep builder | awk -F',' '{print $1}' | awk -F\" '{print $4}')
  ci_image=$(grep x86 ${ci_config} | grep builder | head -n1 | awk '{print $2}')

  if [ "${devcontainer_image}" != "${ci_image}" ]; then
    echo "precommit check failed: devcontainer image[${devcontainer_image}] is different with ci image[${ci_image}]"
    exit 1
  fi
}

function main {
  check_devcontainer_image

  exit 0
}

main $@

